### ISSUE TITLE
No such file or directory: './wikidata/ent_label2id.json'

### ISSUE THREAD

**Issue by shankarp8** [edenbiran/RippleEdits#1]
Hi, thanks very much for the paper and code, I found it to be very interested! I am interested in using this repository for a model editing project, and after attempting to run the code via evaluation.py I got the following error: `No such file or directory: './wikidata/ent_label2id.json` . It therefore appears that this ent_label2id.json file is required, but it doesn't seem to be in the current version of the repository. Is there anything I could do to alleviate this issue? 

Thanks very much for the help in advance!

**Comment by edenbiran** [comment]
Hi, the file has been added :)
