### ISSUE TITLE
Can not found file './generations/sampled_entities_divided_to_buckets_5000.json'

### ISSUE THREAD

**Issue by qizhou000** [edenbiran/RippleEdits#3]
Hello! Thank you for your valuable repository. I want to generate the benchmark from scratch. However, when I run `src/build_benchmark.py`, it returns "No such file or directory:  generations/sampled_entities_divided_to_buckets_5000.json". I think the `sampled_entities_divided_to_buckets_5000.json` is some json file necessary to generate data. Can you provide the file?

**Comment by Elanmarkowitz** [comment]
Bumping this

**Comment by edenbiran** [comment]
The file has been added :)
