### ISSUE TITLE
Could I have the original knowledge triplets ?

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [edenbiran/RippleEdits#6]
Hi Eden, Thanks for the impressive work and making the benchmark open-sourced. I find the data were well-organized and really easy to understand.

Would you mind providing the (maybe the link to) original knowledge triplets that make up the testing cases? By way of example,
For a Compositionality-I testing case: "The name of the capital city of the country Pralayakkad South is associated with is", I want two single-hop triplets : (subject: Pralayakkad South, relation: COUNTRY, target: India) and (subject: India, relation: CAPITAL CITY, target: New Delhi).

Definitely appreciate it if hearing from you.

**Comment by edenbiran** [comment]
Hi, if I understand correctly you are looking for the decomposition of the original knowledge (and not the decomposition expected after the edit)?

If so, then unfortunately we do not have the information readily available. It could be generated by taking the original fact (which is found in the dataset) and composing it with the tested second-hop relation (which can also be found in the dataset) using the Wikidata API.

**Comment by Zhaoyi-Li21** [comment]
Yep that's exactly what I meant. I understand and thanks for your prompt response :D
